
version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: farmzyuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: farmzy
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://farmzyuser:password@db:5432/farmzy
    ports:
      - "4000:4000"
volumes:
  db-data:
